// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBooker.Infrastructure.DbContexts;

#nullable disable

namespace MovieBooker.Infrastructure.Migrations
{
    [DbContext(typeof(MovieBookerDbContext))]
    [Migration("20251230063851_New")]
    partial class New
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieBooker.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<int>("ShowTimeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShowTimeId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MovieBooker.Domain.Entities.BookingSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("SeatId");

                    b.ToTable("BookingSeats");
                });

            modelBuilder.Entity("MovieBooker.Domain.Entities.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Bangalore",
                            Name = "PVR Cinemas"
                        },
                        new
                        {
                            Id = 2,
                            City = "Bangalore",
                            Name = "INOX"
                        });
                });

            modelBuilder.Entity("MovieBooker.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Avengers: Endgame"
                        });
                });

            modelBuilder.Entity("MovieBooker.Domain.Entities.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Screens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            Name = "Audi 1"
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            Name = "Audi 2"
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 2,
                            Name = "Screen 1"
                        });
                });

            modelBuilder.Entity("MovieBooker.Domain.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<int>("ScreenId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBooked = false,
                            ScreenId = 1,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = 2,
                            IsBooked = false,
                            ScreenId = 1,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = 3,
                            IsBooked = false,
                            ScreenId = 1,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = 4,
                            IsBooked = false,
                            ScreenId = 1,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = 5,
                            IsBooked = false,
                            ScreenId = 1,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = 6,
                            IsBooked = false,
                            ScreenId = 2,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = 7,
                            IsBooked = false,
                            ScreenId = 2,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = 8,
                            IsBooked = false,
                            ScreenId = 2,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = 9,
                            IsBooked = false,
                            ScreenId = 2,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = 10,
                            IsBooked = false,
                            ScreenId = 2,
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = 11,
                            IsBooked = false,
                            ScreenId = 3,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = 12,
                            IsBooked = false,
                            ScreenId = 3,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = 13,
                            IsBooked = false,
                            ScreenId = 3,
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = 14,
                            IsBooked = false,
                            ScreenId = 3,
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = 15,
                            IsBooked = false,
                            ScreenId = 3,
                            SeatNumber = "A5"
                        });
                });

            modelBuilder.Entity("MovieBooker.Domain.Entities.ShowTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ScreenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("ScreenId");

                    b.ToTable("ShowTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            ScreenId = 1,
                            StartTime = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 1,
                            ScreenId = 1,
                            StartTime = new DateTime(2025, 1, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 2,
                            ScreenId = 2,
                            StartTime = new DateTime(2025, 1, 1, 18, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 3,
                            ScreenId = 3,
                            StartTime = new DateTime(2025, 1, 1, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MovieBooker.Domain.Entities.Booking", b =>
                {
                    b.HasOne("MovieBooker.Domain.Entities.ShowTime", "ShowTime")
                        .WithMany()
                        .HasForeignKey("ShowTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShowTime");
                });

            modelBuilder.Entity("MovieBooker.Domain.Entities.BookingSeat", b =>
                {
                    b.HasOne("MovieBooker.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBooker.Domain.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("MovieBooker.Domain.Entities.Screen", b =>
                {
                    b.HasOne("MovieBooker.Domain.Entities.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("MovieBooker.Domain.Entities.ShowTime", b =>
                {
                    b.HasOne("MovieBooker.Domain.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBooker.Domain.Entities.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("MovieBooker.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingSeats");
                });
#pragma warning restore 612, 618
        }
    }
}
